# run with:
#   python -m scripts.pipeline --base-config config/base.yaml --override-config config/03_best_trial.yaml --verbose

experiment:
  name: "best_trial_real"     # experiment will go in experiments/best_trial_real/
  seed: 123

training_package:
  include_negatives: true      # negatives are critical
  balance: true
  max_per_class: null          # use all available data
  # keep all qualities + all call types → no filter

training:
  epochs: 50                   # baseline epochs
  batch_size: 32               # stable, not too big for memory
  threads: 4
  val_split: 0.2
  autotune: true               # enable hyperparameter search

inference:
  batch_size: 32
  threads: 4
  min_conf: 0.01               # relaxed for recall

evaluation:
  thresholds: [0.1, 0.2, 0.3, 0.5, 0.7, 0.9]
  output_dir: "evaluation"

# BirdNET CLI passthroughs
training_args:
  fmin: 0
  fmax: 8000                   # frogs rarely above 8 kHz
  overlap: 0.5                 # extra coverage during training

analyzer_args:
  fmin: 0
  fmax: 8000
  overlap: 0.5
  sensitivity: 1.1             # bias for recall in inference
