# 09_autotune_conf075.yaml
experiment:
  name: "09_autotune_conf075"
  seed: 123
training_package:
  include_negatives: true
  balance: true
  max_per_class: null
training:
  epochs: 50
  batch_size: 32
  threads: 4
  val_split: 0.2
  autotune: true
inference:
  batch_size: 32
  threads: 4
  min_conf: 0.75
evaluation:
  thresholds: [0.25, 0.5, 0.75, 0.9]
  output_dir: "evaluation"
