# 13_autotune_bandpass.yaml
experiment:
  name: "13_autotune_bandpass"
  seed: 123
training_package:
  include_negatives: true
  balance: true
  max_per_class: null
training:
  epochs: 50
  batch_size: 32
  threads: 4
  val_split: 0.2
  autotune: true
training_args:
  fmin: 0
  fmax: 6000
analyzer_args:
  fmin: 0
  fmax: 6000
inference:
  batch_size: 32
  threads: 4
  min_conf: 0.05
evaluation:
  thresholds: [0.1, 0.25, 0.5, 0.75]
  output_dir: "evaluation"
