# 14_autotune_loose.yaml
experiment:
  name: "14_autotune_loose"
  seed: 123
training_package:
  include_negatives: true
  balance: true
  max_per_class: null
training:
  epochs: 50
  batch_size: 32
  threads: 4
  val_split: 0.2
  autotune: true
inference:
  batch_size: 32
  threads: 4
  min_conf: 0.01    # extra permissive to boost recall
evaluation:
  thresholds: [0.01, 0.05, 0.1, 0.25, 0.5]
  output_dir: "evaluation"
