# run with:
#   python -m scripts.pipeline --base-config config/base.yaml --override-config config/first_trial_real.yaml --verbose

experiment:
  name: "first_trial_real"     # experiment will go in experiments/first_trial_real/

training_package:
  include_negatives: true      # negatives matter for realistic precision
  balance: true                # balance pos/neg
  max_per_class: null          # no artificial cap, use all available data

training:
  epochs: 50                   # still provide, autotune may override
  batch_size: 32
  threads: 4
  val_split: 0.2
  autotune: true               # enable hyperparameter search

inference:
  batch_size: 32
  threads: 4
  min_conf: 0.05               # slightly relaxed to not filter too aggressively

evaluation:
  thresholds: [0.1, 0.2, 0.3, 0.5, 0.7, 0.9]
  output_dir: "evaluation"
