# run with: python -m scripts.pipeline --base-config config/base.yaml --override-config config/test_quick.yaml --verbose


experiment:
  name: "test_quick_run"   # will go in experiments/test_quick_run/

training_package:
  include_negatives: true
  balance: true
  max_per_class: 100        # small cap so package is built fast
  quality: ["high", "medium"]
  call_type: ["grunt", "growl"]

training:
  epochs: 2                 # very short run
  batch_size: 16            # smaller batch to speed up forward/backward passes
  threads: 2
  val_split: 0.2
  autotune: false           # skip autotune for speed

inference:
  batch_size: 16
  threads: 2
  min_conf: 0.1

evaluation:
  thresholds: [0.3, 0.5, 0.7]   # fewer thresholds, still tests eval
  output_dir: "evaluation"

training_args:
  fmin: 0
  fmax: 8000

analyzer_args:
  fmin: 0
  fmax: 8000
  sensitivity: 1.0
