# ===========================================================
# Base configuration for BirdNET Frog Training pipeline
# -----------------------------------------------------------
# To run new experiments:
#   - Copy this file to config/<experiment_name>.yaml
#   - Change experiment.name to something unique
#   - Override any training, inference, training_args, or analyzer_args values
#   - Run pipeline.py with --override-config config/<experiment_name>.yaml
#
# The training_args and analyzer_args sections are passthroughs:
#   - training_args → forwarded to birdnet_analyzer.train
#   - analyzer_args → forwarded to birdnet_analyzer.analyze
#
# ⚠️ IMPORTANT: Some arguments (e.g., fmin, fmax, overlap) must be 
# set consistently for both training *and* inference. If you use 
# these, make sure to include them in BOTH sections to avoid 
# mismatches between how your model is trained vs. evaluated.
#
# Example:
#
# training_args:
#   fmin: 0
#   fmax: 8000
#   overlap: 0.5
#
# analyzer_args:
#   fmin: 0
#   fmax: 8000
#   overlap: 0.5
#   sensitivity: 1.1
#
# -----------------------------------------------------------
# Explicitly defines BirdNET defaults for clarity.
# Any sweeps or overrides should reference this file.
# -----------------------------------------------------------

dataset:
  audio_root: "AudioData"
  manifest: "data/manifest.csv"

experiment:
  name: "base_experiment"
  seed: 123

training_package:
  include_negatives: true
  balance: true
  max_per_class: null
  quality: ["high", "medium"]   # start simple; low quality can be tested later

training:
  epochs: 50
  batch_size: 32                # BirdNET default = 32
  threads: 4
  val_split: 0.2
  autotune: false

inference:
  batch_size: 32                # BirdNET default = 32
  threads: 4
  min_conf: 0.5                 # BirdNET default = 0.25 (we set 0.5 as stricter baseline)

evaluation:
  thresholds: [0.5]             # Minimal inference threshold (full sweep handled in evaluate_results.py)
  output_dir: "evaluation"

# --- BirdNET Analyzer training_args (explicit defaults) ---
training_args:
  fmin: 0                       # BirdNET default
  fmax: 15000                   # BirdNET default
  overlap: 0.0                  # BirdNET default
  dropout: 0.25          # fixed anchor
  hidden_units: 512      # fixed anchor
  learning_rate: 0.0005  # fixed anchor
  focal-loss: false             # BirdNET default
  focal-loss-gamma: 2.0         # BirdNET default
  focal-loss-alpha: 0.25        # BirdNET default
  label_smoothing: false        # BirdNET default
  mixup: false                  # BirdNET default
  upsampling_ratio: 0.0         # BirdNET default
  upsampling_mode: repeat       # BirdNET default

# --- BirdNET Analyzer inference_args (explicit defaults) ---
analyzer_args:
  fmin: 0                       # BirdNET default
  fmax: 15000                   # BirdNET default
  overlap: 0.0                   # BirdNET default
  sensitivity: 1.0              # BirdNET default
