# configs/base.yaml
dataset:
  audio_root: "AudioData"                  # where your raw/split audio lives
  manifest: "data/manifest.csv" # the source of truth for splits

training_package:
  out_root: "training_packages"            # where packages get written
  include_negatives: true
  balance: false
  max_per_class: null
  seed: 123

training:
  epochs: 50
  batch_size: 64
  threads: 4
  val_split: 0.2
  autotune: false

inference:
  batch_size: 64
  threads: 4
  min_conf: 0.01

evaluation:
  thresholds: [0.0, 0.05, 0.1, 0.2, 0.3, 0.5, 0.7, 0.9, 1.0]
  output_dir: "evaluation"
